// AUTO-GENERATED by scripts/fetch-unsplash.mjs — do not edit by hand.
// Re-run `npm run fetch-images -- --query "..."` to refresh.

export type UnsplashImage = {
    id: string;
    query: string;
    collection: string;
    /** Path under /public — use directly as an <img src>. */
    file: string;
    width: number;
    height: number;
    color: string;
    alt: string;
    credit: { name: string; username: string; profile: string; photo: string };
};

export const unsplashImages: UnsplashImage[] = [
    {
        "id": "jyoSxjUE22g",
        "query": "programmatic advertising",
        "collection": "programmatic-advertising",
        "file": "/unsplash/programmatic-advertising/programmatic-advertising-jyoSxjUE22g.jpg",
        "width": 3977,
        "height": 2983,
        "color": "#f3f3f3",
        "alt": "multicolored marketing freestanding letter",
        "credit": {
            "name": "Merakist",
            "username": "merakist",
            "profile": "https://unsplash.com/@merakist?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/multicolored-marketing-freestanding-letter-jyoSxjUE22g?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "ZQZrvL7DwiI",
        "query": "programmatic advertising",
        "collection": "programmatic-advertising",
        "file": "/unsplash/programmatic-advertising/programmatic-advertising-ZQZrvL7DwiI.jpg",
        "width": 6000,
        "height": 4000,
        "color": "#0c2626",
        "alt": "a bunch of billboards that are on the side of a building",
        "credit": {
            "name": "Deon Fosu",
            "username": "deonfosu",
            "profile": "https://unsplash.com/@deonfosu?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/a-bunch-of-billboards-that-are-on-the-side-of-a-building-ZQZrvL7DwiI?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "MjVq8u7bHhM",
        "query": "programmatic advertising",
        "collection": "programmatic-advertising",
        "file": "/unsplash/programmatic-advertising/programmatic-advertising-MjVq8u7bHhM.jpg",
        "width": 4453,
        "height": 2973,
        "color": "#f3f3f3",
        "alt": "Billboard with \"agents echo. echo. echo. you play.\"",
        "credit": {
            "name": "Igor Shalyminov",
            "username": "ishalyminov",
            "profile": "https://unsplash.com/@ishalyminov?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/billboard-with-agents-echo-echo-echo-you-play-MjVq8u7bHhM?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "RE5UB9z4Ev8",
        "query": "programmatic advertising",
        "collection": "programmatic-advertising",
        "file": "/unsplash/programmatic-advertising/programmatic-advertising-RE5UB9z4Ev8.jpg",
        "width": 5184,
        "height": 3456,
        "color": "#262626",
        "alt": "calendar",
        "credit": {
            "name": "Nathan Jeon",
            "username": "nathanj_",
            "profile": "https://unsplash.com/@nathanj_?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/calendar-RE5UB9z4Ev8?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "rV-PntikRPk",
        "query": "programmatic advertising",
        "collection": "programmatic-advertising",
        "file": "/unsplash/programmatic-advertising/programmatic-advertising-rV-PntikRPk.jpg",
        "width": 5184,
        "height": 2920,
        "color": "#0c2626",
        "alt": "people walking on street during night time",
        "credit": {
            "name": "Chris Kursikowski",
            "username": "c3k",
            "profile": "https://unsplash.com/@c3k?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/people-walking-on-street-during-night-time-rV-PntikRPk?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "9e9PD9blAto",
        "query": "mobile phone app technology",
        "collection": "mobile-phone-app-technology",
        "file": "/unsplash/mobile-phone-app-technology/mobile-phone-app-technology-9e9PD9blAto.jpg",
        "width": 5184,
        "height": 3456,
        "color": "#a6c0c0",
        "alt": "space gray iPhone X",
        "credit": {
            "name": "William Hook",
            "username": "williamtm",
            "profile": "https://unsplash.com/@williamtm?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/space-gray-iphone-x-9e9PD9blAto?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "w33-zg-dNL4",
        "query": "mobile phone app technology",
        "collection": "mobile-phone-app-technology",
        "file": "/unsplash/mobile-phone-app-technology/mobile-phone-app-technology-w33-zg-dNL4.jpg",
        "width": 5184,
        "height": 3456,
        "color": "#262626",
        "alt": "silver Android smartphone",
        "credit": {
            "name": "Rami Al-zayat",
            "username": "rami_alzayat",
            "profile": "https://unsplash.com/@rami_alzayat?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/silver-android-smartphone-w33-zg-dNL4?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "q8U1YgBaRQk",
        "query": "mobile phone app technology",
        "collection": "mobile-phone-app-technology",
        "file": "/unsplash/mobile-phone-app-technology/mobile-phone-app-technology-q8U1YgBaRQk.jpg",
        "width": 5032,
        "height": 3355,
        "color": "#d9d9d9",
        "alt": "person holding white Android smartphone in white shirt",
        "credit": {
            "name": "NordWood Themes",
            "username": "nordwood",
            "profile": "https://unsplash.com/@nordwood?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/person-holding-white-android-smartphone-in-white-shirt-q8U1YgBaRQk?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "sScmok4Iq1o",
        "query": "mobile phone app technology",
        "collection": "mobile-phone-app-technology",
        "file": "/unsplash/mobile-phone-app-technology/mobile-phone-app-technology-sScmok4Iq1o.jpg",
        "width": 4843,
        "height": 3632,
        "color": "#f3f3f3",
        "alt": "black Android smartphone",
        "credit": {
            "name": "Balázs Kétyi",
            "username": "balazsketyi",
            "profile": "https://unsplash.com/@balazsketyi?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/black-android-smartphone-sScmok4Iq1o?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "n31x0hhnzOs",
        "query": "mobile phone app technology",
        "collection": "mobile-phone-app-technology",
        "file": "/unsplash/mobile-phone-app-technology/mobile-phone-app-technology-n31x0hhnzOs.jpg",
        "width": 5760,
        "height": 3240,
        "color": "#d9d9d9",
        "alt": "person holding space gray iPhone X",
        "credit": {
            "name": "Yura Fresh",
            "username": "mr_fresh",
            "profile": "https://unsplash.com/@mr_fresh?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/person-holding-space-gray-iphone-x-n31x0hhnzOs?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "0VGG7cqTwCo",
        "query": "mobile phone app technology",
        "collection": "mobile-phone-app-technology",
        "file": "/unsplash/mobile-phone-app-technology/mobile-phone-app-technology-0VGG7cqTwCo.jpg",
        "width": 6000,
        "height": 4000,
        "color": "#262640",
        "alt": "person holding smartphone",
        "credit": {
            "name": "Rodion Kutsaiev",
            "username": "frostroomhead",
            "profile": "https://unsplash.com/@frostroomhead?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/person-holding-smartphone-0VGG7cqTwCo?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "QwAL909kTiY",
        "query": "mobile phone app technology",
        "collection": "mobile-phone-app-technology",
        "file": "/unsplash/mobile-phone-app-technology/mobile-phone-app-technology-QwAL909kTiY.jpg",
        "width": 6000,
        "height": 4000,
        "color": "#f3f3f3",
        "alt": "person holding black android smartphone",
        "credit": {
            "name": "Tran Mau Tri Tam ✪",
            "username": "tranmautritam",
            "profile": "https://unsplash.com/@tranmautritam?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/person-holding-black-android-smartphone-QwAL909kTiY?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "JKUTrJ4vK00",
        "query": "data analytics dashboard screen",
        "collection": "data-analytics-dashboard-screen",
        "file": "/unsplash/data-analytics-dashboard-screen/data-analytics-dashboard-screen-JKUTrJ4vK00.jpg",
        "width": 4810,
        "height": 3207,
        "color": "#f3f3f3",
        "alt": "graphs of performance analytics on a laptop screen",
        "credit": {
            "name": "Luke Chesser",
            "username": "lukechesser",
            "profile": "https://unsplash.com/@lukechesser?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/graphs-of-performance-analytics-on-a-laptop-screen-JKUTrJ4vK00?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "tR0jvlsmCuQ",
        "query": "data analytics dashboard screen",
        "collection": "data-analytics-dashboard-screen",
        "file": "/unsplash/data-analytics-dashboard-screen/data-analytics-dashboard-screen-tR0jvlsmCuQ.jpg",
        "width": 3370,
        "height": 2527,
        "color": "#f3f3f3",
        "alt": "black and silver laptop computer",
        "credit": {
            "name": "path digital",
            "username": "pathdigital",
            "profile": "https://unsplash.com/@pathdigital?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/black-and-silver-laptop-computer-tR0jvlsmCuQ?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "hpjSkU2UYSU",
        "query": "data analytics dashboard screen",
        "collection": "data-analytics-dashboard-screen",
        "file": "/unsplash/data-analytics-dashboard-screen/data-analytics-dashboard-screen-hpjSkU2UYSU.jpg",
        "width": 2426,
        "height": 1728,
        "color": "#404040",
        "alt": "laptop computer on glass-top table",
        "credit": {
            "name": "Carlos Muza",
            "username": "kmuza",
            "profile": "https://unsplash.com/@kmuza?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/laptop-computer-on-glass-top-table-hpjSkU2UYSU?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "qwtCeJ5cLYs",
        "query": "data analytics dashboard screen",
        "collection": "data-analytics-dashboard-screen",
        "file": "/unsplash/data-analytics-dashboard-screen/data-analytics-dashboard-screen-qwtCeJ5cLYs.jpg",
        "width": 2947,
        "height": 2121,
        "color": "#595959",
        "alt": "turned on monitoring screen",
        "credit": {
            "name": "Stephen Dawson",
            "username": "dawson2406",
            "profile": "https://unsplash.com/@dawson2406?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/turned-on-monitoring-screen-qwtCeJ5cLYs?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "shr_Xn8S8QU",
        "query": "data analytics dashboard screen",
        "collection": "data-analytics-dashboard-screen",
        "file": "/unsplash/data-analytics-dashboard-screen/data-analytics-dashboard-screen-shr_Xn8S8QU.jpg",
        "width": 4688,
        "height": 2860,
        "color": "#d9d9d9",
        "alt": "monitor screengrab",
        "credit": {
            "name": "Stephen Phillips - Hostreviews.co.uk",
            "username": "hostreviews",
            "profile": "https://unsplash.com/@hostreviews?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/monitor-screengrab-shr_Xn8S8QU?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "bMWHu8wU1Vk",
        "query": "data analytics dashboard screen",
        "collection": "data-analytics-dashboard-screen",
        "file": "/unsplash/data-analytics-dashboard-screen/data-analytics-dashboard-screen-bMWHu8wU1Vk.jpg",
        "width": 5687,
        "height": 3791,
        "color": "#d9d9d9",
        "alt": "a computer screen with a bunch of data on it",
        "credit": {
            "name": "1981 Digital",
            "username": "1981digital",
            "profile": "https://unsplash.com/@1981digital?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/a-computer-screen-with-a-bunch-of-data-on-it-bMWHu8wU1Vk?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "mcSDtbWXUZU",
        "query": "data analytics dashboard screen",
        "collection": "data-analytics-dashboard-screen",
        "file": "/unsplash/data-analytics-dashboard-screen/data-analytics-dashboard-screen-mcSDtbWXUZU.jpg",
        "width": 6144,
        "height": 4069,
        "color": "#f3f3f3",
        "alt": "turned on black and grey laptop computer",
        "credit": {
            "name": "Lukas Blazek",
            "username": "goumbik",
            "profile": "https://unsplash.com/@goumbik?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/turned-on-black-and-grey-laptop-computer-mcSDtbWXUZU?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "r5lbaK3fDaM",
        "query": "abstract technology gradient blue",
        "collection": "abstract-technology-gradient-blue",
        "file": "/unsplash/abstract-technology-gradient-blue/abstract-technology-gradient-blue-r5lbaK3fDaM.jpg",
        "width": 7680,
        "height": 4320,
        "color": "#0c2640",
        "alt": "Abstract blue glowing dots forming wave patterns",
        "credit": {
            "name": "jonakoh _",
            "username": "jonakoh",
            "profile": "https://unsplash.com/@jonakoh?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/abstract-blue-glowing-dots-forming-wave-patterns-r5lbaK3fDaM?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "6EQZ2JcHZmk",
        "query": "abstract technology gradient blue",
        "collection": "abstract-technology-gradient-blue",
        "file": "/unsplash/abstract-technology-gradient-blue/abstract-technology-gradient-blue-6EQZ2JcHZmk.jpg",
        "width": 7680,
        "height": 4320,
        "color": "#2640a6",
        "alt": "Abstract flowing lines with gradient colors.",
        "credit": {
            "name": "Logan Voss",
            "username": "loganvoss",
            "profile": "https://unsplash.com/@loganvoss?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/abstract-flowing-lines-with-gradient-colors-6EQZ2JcHZmk?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "attaiMHl274",
        "query": "abstract technology gradient blue",
        "collection": "abstract-technology-gradient-blue",
        "file": "/unsplash/abstract-technology-gradient-blue/abstract-technology-gradient-blue-attaiMHl274.jpg",
        "width": 7680,
        "height": 4320,
        "color": "#0c26a6",
        "alt": "Abstract blue and black light streaks",
        "credit": {
            "name": "Alexander X.",
            "username": "23exe",
            "profile": "https://unsplash.com/@23exe?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/abstract-blue-and-black-light-streaks-attaiMHl274?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "lYYodOFWvn0",
        "query": "abstract technology gradient blue",
        "collection": "abstract-technology-gradient-blue",
        "file": "/unsplash/abstract-technology-gradient-blue/abstract-technology-gradient-blue-lYYodOFWvn0.jpg",
        "width": 7680,
        "height": 4320,
        "color": "#0c26a6",
        "alt": "Abstract blue light streaks on dark background",
        "credit": {
            "name": "Alexander X.",
            "username": "23exe",
            "profile": "https://unsplash.com/@23exe?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/abstract-blue-light-streaks-on-dark-background-lYYodOFWvn0?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "dGN0ZrJvaOk",
        "query": "abstract technology gradient blue",
        "collection": "abstract-technology-gradient-blue",
        "file": "/unsplash/abstract-technology-gradient-blue/abstract-technology-gradient-blue-dGN0ZrJvaOk.jpg",
        "width": 7680,
        "height": 4320,
        "color": "#0c2626",
        "alt": "A blue and black abstract pattern.",
        "credit": {
            "name": "Logan Voss",
            "username": "loganvoss",
            "profile": "https://unsplash.com/@loganvoss?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/a-blue-and-black-abstract-pattern-dGN0ZrJvaOk?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "FpC3XIFM2Bg",
        "query": "abstract technology gradient blue",
        "collection": "abstract-technology-gradient-blue",
        "file": "/unsplash/abstract-technology-gradient-blue/abstract-technology-gradient-blue-FpC3XIFM2Bg.jpg",
        "width": 3840,
        "height": 2160,
        "color": "#0c2640",
        "alt": "Concentric circles of light on a dark blue background",
        "credit": {
            "name": "PixelPro Vibes",
            "username": "pixelprovibes",
            "profile": "https://unsplash.com/@pixelprovibes?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/concentric-circles-of-light-on-a-dark-blue-background-FpC3XIFM2Bg?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "eEjlchmojyU",
        "query": "abstract technology gradient blue",
        "collection": "abstract-technology-gradient-blue",
        "file": "/unsplash/abstract-technology-gradient-blue/abstract-technology-gradient-blue-eEjlchmojyU.jpg",
        "width": 7680,
        "height": 4320,
        "color": "#0cf3f3",
        "alt": "Abstract blue and black glowing waves",
        "credit": {
            "name": "Akif Waseem",
            "username": "akif_waseem",
            "profile": "https://unsplash.com/@akif_waseem?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/abstract-blue-and-black-glowing-waves-eEjlchmojyU?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "JXDtZxhdX9Y",
        "query": "advertising billboard city",
        "collection": "advertising-billboard-city",
        "file": "/unsplash/advertising-billboard-city/advertising-billboard-city-JXDtZxhdX9Y.jpg",
        "width": 3600,
        "height": 2400,
        "color": "#f3f3f3",
        "alt": "black and gray bicycle on road during daytime",
        "credit": {
            "name": "bram naus",
            "username": "bramnaus",
            "profile": "https://unsplash.com/@bramnaus?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/black-and-gray-bicycle-on-road-during-daytime-JXDtZxhdX9Y?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "jiEIu4TH-7s",
        "query": "advertising billboard city",
        "collection": "advertising-billboard-city",
        "file": "/unsplash/advertising-billboard-city/advertising-billboard-city-jiEIu4TH-7s.jpg",
        "width": 5328,
        "height": 4000,
        "color": "#598cc0",
        "alt": "a tall metal pole with a sign on top of it",
        "credit": {
            "name": "Rick Alday",
            "username": "rickalday",
            "profile": "https://unsplash.com/@rickalday?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/a-tall-metal-pole-with-a-sign-on-top-of-it-jiEIu4TH-7s?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "bPHY2KV1Oe4",
        "query": "advertising billboard city",
        "collection": "advertising-billboard-city",
        "file": "/unsplash/advertising-billboard-city/advertising-billboard-city-bPHY2KV1Oe4.jpg",
        "width": 6000,
        "height": 4000,
        "color": "#a6c0d9",
        "alt": "Billboard displays a sky scene.",
        "credit": {
            "name": "John Maldonado",
            "username": "johnmaldonado",
            "profile": "https://unsplash.com/@johnmaldonado?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/billboard-displays-a-sky-scene-bPHY2KV1Oe4?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "5GBvm1lhrFM",
        "query": "advertising billboard city",
        "collection": "advertising-billboard-city",
        "file": "/unsplash/advertising-billboard-city/advertising-billboard-city-5GBvm1lhrFM.jpg",
        "width": 5712,
        "height": 4284,
        "color": "#0c4059",
        "alt": "Large illuminated billboards on a building at dusk.",
        "credit": {
            "name": "John Cameron",
            "username": "john_cameron",
            "profile": "https://unsplash.com/@john_cameron?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/large-illuminated-billboards-on-a-building-at-dusk-5GBvm1lhrFM?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "qUTh9UHcyeI",
        "query": "advertising billboard city",
        "collection": "advertising-billboard-city",
        "file": "/unsplash/advertising-billboard-city/advertising-billboard-city-qUTh9UHcyeI.jpg",
        "width": 5472,
        "height": 3648,
        "color": "#a6d9f3",
        "alt": "Sign with repeating word \"essen\" against blue sky",
        "credit": {
            "name": "pott mockups",
            "username": "pottmockups",
            "profile": "https://unsplash.com/@pottmockups?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/sign-with-repeating-word-essen-against-blue-sky-qUTh9UHcyeI?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "lVgE1Ps1m2g",
        "query": "advertising billboard city",
        "collection": "advertising-billboard-city",
        "file": "/unsplash/advertising-billboard-city/advertising-billboard-city-lVgE1Ps1m2g.jpg",
        "width": 4674,
        "height": 3116,
        "color": "#260c0c",
        "alt": "A sign with the word \"essen\" repeated many times.",
        "credit": {
            "name": "pott mockups",
            "username": "pottmockups",
            "profile": "https://unsplash.com/@pottmockups?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/a-sign-with-the-word-essen-repeated-many-times-lVgE1Ps1m2g?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "VvQCVz93EJ8",
        "query": "advertising billboard city",
        "collection": "advertising-billboard-city",
        "file": "/unsplash/advertising-billboard-city/advertising-billboard-city-VvQCVz93EJ8.jpg",
        "width": 5472,
        "height": 3648,
        "color": "#262626",
        "alt": "a man walking across a street at night",
        "credit": {
            "name": "glenn pajarito",
            "username": "glennnnyc",
            "profile": "https://unsplash.com/@glennnnyc?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/a-man-walking-across-a-street-at-night-VvQCVz93EJ8?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "l90zRbWvCoE",
        "query": "modern office business team",
        "collection": "modern-office-business-team",
        "file": "/unsplash/modern-office-business-team/modern-office-business-team-l90zRbWvCoE.jpg",
        "width": 5772,
        "height": 3848,
        "color": "#d9d9d9",
        "alt": "man standing beside another sitting man using computer",
        "credit": {
            "name": "Proxyclick Visitor Management System",
            "username": "proxyclick",
            "profile": "https://unsplash.com/@proxyclick?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/man-standing-beside-another-sitting-man-using-computer-l90zRbWvCoE?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "rtD_lcsN6_U",
        "query": "modern office business team",
        "collection": "modern-office-business-team",
        "file": "/unsplash/modern-office-business-team/modern-office-business-team-rtD_lcsN6_U.jpg",
        "width": 4032,
        "height": 2688,
        "color": "#c0c0c0",
        "alt": "a group of people sitting around a table with laptops",
        "credit": {
            "name": "Lyubomyr Reverchuk",
            "username": "lreverchuk",
            "profile": "https://unsplash.com/@lreverchuk?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/a-group-of-people-sitting-around-a-table-with-laptops-rtD_lcsN6_U?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "2pPw5Glro5I",
        "query": "modern office business team",
        "collection": "modern-office-business-team",
        "file": "/unsplash/modern-office-business-team/modern-office-business-team-2pPw5Glro5I.jpg",
        "width": 4096,
        "height": 2730,
        "color": "#c0c0c0",
        "alt": "people sitting at the table",
        "credit": {
            "name": "Memento Media",
            "username": "heymemento",
            "profile": "https://unsplash.com/@heymemento?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/people-sitting-at-the-table-2pPw5Glro5I?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "yd_RKGH_RH4",
        "query": "modern office business team",
        "collection": "modern-office-business-team",
        "file": "/unsplash/modern-office-business-team/modern-office-business-team-yd_RKGH_RH4.jpg",
        "width": 3840,
        "height": 2160,
        "color": "#262626",
        "alt": "Diverse team collaborating around a laptop in office.",
        "credit": {
            "name": "Vitaly Gariev",
            "username": "silverkblack",
            "profile": "https://unsplash.com/@silverkblack?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/diverse-team-collaborating-around-a-laptop-in-office-yd_RKGH_RH4?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "gItonyvrdUA",
        "query": "modern office business team",
        "collection": "modern-office-business-team",
        "file": "/unsplash/modern-office-business-team/modern-office-business-team-gItonyvrdUA.jpg",
        "width": 3800,
        "height": 2138,
        "color": "#8ca6a6",
        "alt": "Four professionals in business attire stand together.",
        "credit": {
            "name": "Vitaly Gariev",
            "username": "silverkblack",
            "profile": "https://unsplash.com/@silverkblack?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/four-professionals-in-business-attire-stand-together-gItonyvrdUA?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "q1jHh0MWTFk",
        "query": "modern office business team",
        "collection": "modern-office-business-team",
        "file": "/unsplash/modern-office-business-team/modern-office-business-team-q1jHh0MWTFk.jpg",
        "width": 3840,
        "height": 2160,
        "color": "#c0c0c0",
        "alt": "Diverse group of professionals standing together indoors.",
        "credit": {
            "name": "Vitaly Gariev",
            "username": "silverkblack",
            "profile": "https://unsplash.com/@silverkblack?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/diverse-group-of-professionals-standing-together-indoors-q1jHh0MWTFk?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "EcEp6_kYyYM",
        "query": "modern office business team",
        "collection": "modern-office-business-team",
        "file": "/unsplash/modern-office-business-team/modern-office-business-team-EcEp6_kYyYM.jpg",
        "width": 3600,
        "height": 2400,
        "color": "#c0c0c0",
        "alt": "Men working on computers in a modern office.",
        "credit": {
            "name": "João Victor da Silva Ribeiro",
            "username": "rjoaovictorbhmg",
            "profile": "https://unsplash.com/@rjoaovictorbhmg?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/men-working-on-computers-in-a-modern-office-EcEp6_kYyYM?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "pgdaAwf6IJg",
        "query": "server network data center",
        "collection": "server-network-data-center",
        "file": "/unsplash/server-network-data-center/server-network-data-center-pgdaAwf6IJg.jpg",
        "width": 4581,
        "height": 3064,
        "color": "#404040",
        "alt": "black ImgIX server system",
        "credit": {
            "name": "imgix",
            "username": "imgix",
            "profile": "https://unsplash.com/@imgix?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/black-imgix-server-system-pgdaAwf6IJg?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "VHmBX7FnXw0",
        "query": "server network data center",
        "collection": "server-network-data-center",
        "file": "/unsplash/server-network-data-center/server-network-data-center-VHmBX7FnXw0.jpg",
        "width": 4928,
        "height": 3264,
        "color": "#262626",
        "alt": "Server rack with blinking green lights",
        "credit": {
            "name": "Domaintechnik",
            "username": "fslfsl",
            "profile": "https://unsplash.com/@fslfsl?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/server-rack-with-blinking-green-lights-VHmBX7FnXw0?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "HQfuZERbbzE",
        "query": "server network data center",
        "collection": "server-network-data-center",
        "file": "/unsplash/server-network-data-center/server-network-data-center-HQfuZERbbzE.jpg",
        "width": 4592,
        "height": 2245,
        "color": "#c0c0c0",
        "alt": "grayscale photography of rectangular gray case on wire rack",
        "credit": {
            "name": "imgix",
            "username": "imgix",
            "profile": "https://unsplash.com/@imgix?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/grayscale-photography-of-rectangular-gray-case-on-wire-rack-HQfuZERbbzE?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "y4GHs9GEFdM",
        "query": "server network data center",
        "collection": "server-network-data-center",
        "file": "/unsplash/server-network-data-center/server-network-data-center-y4GHs9GEFdM.jpg",
        "width": 5333,
        "height": 3555,
        "color": "#262626",
        "alt": "Ethernet cables connected to the back of a network device.",
        "credit": {
            "name": "Manuel Luikenga",
            "username": "manuel_luikenga",
            "profile": "https://unsplash.com/@manuel_luikenga?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/ethernet-cables-connected-to-the-back-of-a-network-device-y4GHs9GEFdM?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "iZe21DzHnUg",
        "query": "server network data center",
        "collection": "server-network-data-center",
        "file": "/unsplash/server-network-data-center/server-network-data-center-iZe21DzHnUg.jpg",
        "width": 7008,
        "height": 4672,
        "color": "#c0c0f3",
        "alt": "Close-up of server cooling fans in a vibrant data center.",
        "credit": {
            "name": "Winston Chen",
            "username": "winstonchen",
            "profile": "https://unsplash.com/@winstonchen?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/close-up-of-server-cooling-fans-in-a-vibrant-data-center-iZe21DzHnUg?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "nA1MoDfGY14",
        "query": "server network data center",
        "collection": "server-network-data-center",
        "file": "/unsplash/server-network-data-center/server-network-data-center-nA1MoDfGY14.jpg",
        "width": 4256,
        "height": 2832,
        "color": "#0c260c",
        "alt": "black and white electronic device",
        "credit": {
            "name": "Elimende Inagella",
            "username": "elimendeinagella",
            "profile": "https://unsplash.com/@elimendeinagella?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/black-and-white-electronic-device-nA1MoDfGY14?utm_source=nimbus_design_system&utm_medium=referral"
        }
    },
    {
        "id": "GjBPLkTDzt4",
        "query": "server network data center",
        "collection": "server-network-data-center",
        "file": "/unsplash/server-network-data-center/server-network-data-center-GjBPLkTDzt4.jpg",
        "width": 6310,
        "height": 3935,
        "color": "#8c4059",
        "alt": "chart, treemap chart",
        "credit": {
            "name": "Ben Wicks",
            "username": "profwicks",
            "profile": "https://unsplash.com/@profwicks?utm_source=nimbus_design_system&utm_medium=referral",
            "photo": "https://unsplash.com/photos/chart-treemap-chart-GjBPLkTDzt4?utm_source=nimbus_design_system&utm_medium=referral"
        }
    }
];

/** All images tagged with a given collection slug. */
export const imagesByCollection = (collection: string) => unsplashImages.filter((i) => i.collection === collection);
